### ISSUE TITLE
Hash-utils dependency

### ISSUE THREAD

**Issue by netDalek** [martinkozak/json-rpc-objects#1]
Hello, great work and thanks for it. I'm writing you because I cought some conflict in my rails project. After adding the gem I got error: "gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in `require': cannot load such file -- p (LoadError)". I didn't digged deep, I've just found that it is because some additions for ruby String class in hash-utils gem. So I forked this project and got rid of hash-utils gem. There are only few uses of it. Probably it is better for json-rpc-objects not to use any patches for standard ruby classes. What do you think about that?

**Comment by martinpoljak** [comment]
Dependency to `hash-utils` gem has been completely removed since version `0.4.5`. Thank You.
